name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  terraform_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate

      - name: Format Terraform code
        run: terraform fmt -check

      - name: Plan Terraform deployment
        run: terraform plan

      - name: Apply Terraform changes
        run: terraform apply --auto-approve

      - name: Destroy Terraform resources (optional)
        run: terraform destroy --auto-approve