name: Terraform Infrastructure Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format Check
        run: |
          find . -name '*.tf' -type f -print0 | xargs -0 -n1 terraform fmt -check=true

  deploy:
    needs: lint
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' && needs.lint.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud components update

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Google Cloud authentication
        uses: google-github-actions/auth@v0.4.2
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Terraform Init
        run: terraform init

      - name: Run Terraform Plan
        run: terraform plan

      - name: Run Terraform Apply
        run: terraform apply -auto-approve